version: "3.7"
networks:
  quarkus-mongo:
    external: true

services:

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - /home/barry/mongodb/database:/data/db
    environment:
      MONGO_INITDB_DATABASE: management
    ports:
      - "27017:27017"
    restart: always
    networks:
      - quarkus-mongo

  app:
    image: quarkus
    container_name: quarkus
    ports:
      - "8080:8080"
    environment:
      MONGO_INITDB_DATABASE: management
    depends_on:
      - mongodb
      - zookeeper
      - kafka
    networks:
      - quarkus-mongo

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - quarkus-mongo

  kafka:
    image: confluentinc/cp-enterprise-kafka:6.0.0
    hostname: kafka
    restart: "always"
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: |
        PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: |
        PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - quarkus-mongo




