version: "3.7"
networks:
  quarkus-mongo:
    external: true

services:

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - /home/barry/mongodb/database:/data/db
    environment:
      MONGO_INITDB_DATABASE: management
    ports:
      - "27017:27017"
    restart: always
    networks:
      - quarkus-mongo
  app:
    image: quarkus
    container_name: quarkus
    ports:
      - "8080:8080"
    environment:
      MONGO_INITDB_DATABASE: management
    depends_on:
      - mongodb
    networks:
      - quarkus-mongo



